export const pricingPlans = [
  {
    id: 1,
    name: "Osnovni plan",
    price: "$79",
    frequency: "/mesečno",
    description: "Savršen za stambene korisnike",
    features: [
      "Jedna godišnja inspekcija",
      "Prioritetna korisnička podrška",
      "10% popusta na popravke",
      "Uključena zamena filtera",
      "Podrška putem e-pošte",
    ],
    color: "blue",
    popular: false,
  },
  {
    id: 2,
    name: "Profesionalni plan",
    price: "$129",
    frequency: "/mesečno",
    description: "Najpopularniji za stambene korisnike",
    features: [
      "Dve godišnje inspekcije",
      "24/7 prioritetna podrška",
      "20% popusta na popravke",
      "Kvartalna zamena filtera",
      "Podrška putem telefona i e-pošte",
      "Prioritet za hitne intervencije",
      "Optimizacija sistema za energetsku efikasnost",
    ],
    color: "green",
    popular: true,
  },
  {
    id: 3,
    name: "Premium plan",
    price: "$199",
    frequency: "/mesečno",
    description: "Za komercijalne objekte i zahtevne korisnike",
    features: [
      "Kvartalne inspekcije",
      "24/7 hitna podrška garantovana",
      "25% popusta na sve popravke",
      "Mesečna zamena filtera",
      "Posvećeni menadžer naloga",
      "Izveštaji o performansama sistema",
      "Besplatno čišćenje kanala godišnje",
    ],
    color: "purple",
    popular: false,
  },
];
