export const testimonials = [
  {
    id: 1,
    name: "John Smith",
    title: "Homeowner",
    text: "CoolAir installed our new AC system and the service was incredible. Highly professional and they finished ahead of schedule!",
    rating: 5,
    image: "👨",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    title: "Business Owner",
    text: "We've been using CoolAir for commercial maintenance for 3 years. They're reliable, punctual, and reasonably priced.",
    rating: 5,
    image: "👩",
  },
  {
    id: 3,
    name: "Mike Davis",
    title: "Property Manager",
    text: "Emergency service at 2 AM and they were here in 30 minutes. Great staff and fixed our furnace completely.",
    rating: 5,
    image: "👨",
  },
  {
    id: 4,
    name: "Emily Rodriguez",
    title: "Homeowner",
    text: "The thermostat installation was smooth. They explained everything and even showed me how to use the smart features.",
    rating: 5,
    image: "👩",
  },
  {
    id: 5,
    name: "Robert Chen",
    title: "Restaurant Owner",
    text: "Excellent service for our walk-in coolers. CoolAir keeps our business running smoothly.",
    rating: 5,
    image: "👨",
  },
];
